import {readFile, writeFile, mkdir, cp, rm, lstat} from 'node:fs/promises';
import path from 'node:path';
import {validatePublication} from './publication.mjs';
import {fileURLToPath} from 'node:url';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages = [{path:'/',name:'홈'},{path:'/games/kingdom-idle/',name:'왕국군 키우기'},{path:'/studio/',name:'스튜디오'},{path:'/support/',name:'고객지원'},{path:'/policies/',name:'정책 안내'},{path:'/privacy/',name:'개인정보처리방침'},{path:'/terms/',name:'서비스 이용약관'},{path:'/delete-account/',name:'계정 삭제'},{path:'/probabilities/',name:'확률 정보'}];
const arrow = '<span aria-hidden="true">↗</span>';
const link = (href,text,cls='button') => `<a class="${cls}" href="${href}">${text}${arrow}</a>`;
const logo = `<span class="wordmark">LUDOS<span>INTERACTIVE</span></span>`;
const art = (mobile=false) => `<picture class="world-art">${mobile?'<source media="(max-width:760px)" srcset="/assets/kingdom-hero-mobile.webp">':''}<img src="/assets/kingdom-hero-1536.webp" srcset="/assets/kingdom-hero-1024.webp 1024w, /assets/kingdom-hero-1536.webp 1536w" sizes="${mobile?'100vw':'(max-width:760px) 100vw, 60vw'}" alt="성으로 이어지는 숲길과 하늘을 나는 용, 왕국군 키우기 배경 원화" width="1536" height="864" ${mobile?'fetchpriority="high"':'loading="lazy"'} decoding="async"></picture>`;
const gallery = () => [['battle','왕국군의 전투'],['mage','마탑 스킬 육성'],['equipment','장비 뽑기 안내']].map(([asset,caption])=>`<figure><button data-enlarge aria-label="${caption} 화면 크게 보기"><img src="/assets/gameplay-${asset}.webp" width="1080" height="2316" alt="${caption} — 실제 Android 개발 화면" loading="lazy" decoding="async"></button><figcaption>${caption}<span aria-hidden="true"> ↗</span></figcaption></figure>`).join('');

function header(active){return `<a class="skip" href="#main">본문 바로가기</a><header class="site-header"><a class="brand" href="/" aria-label="Ludos Interactive 홈">${logo}</a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav"><span>메뉴</span><i aria-hidden="true"></i></button><nav id="primary-nav" aria-label="주 메뉴"><a href="/games/kingdom-idle/" ${active.includes('/games/')?'aria-current="page"':''}>게임</a><a href="/studio/" ${active==='/studio/'?'aria-current="page"':''}>스튜디오</a><a href="/support/" ${active==='/support/'?'aria-current="page"':''}>고객지원</a><a class="nav-policy" href="/policies/">정책 안내 ${arrow}</a></nav></header>`;}
function footer(c){return `<footer class="site-footer"><div class="footer-top"><a class="brand" href="/" aria-label="Ludos Interactive 홈">${logo}</a><p>작은 선택에서 시작되는, 오래 이어질 모험.</p></div><div class="footer-links"><a href="/privacy/">개인정보처리방침</a><a href="/terms/">이용약관</a><a href="/delete-account/">계정 삭제</a><a href="/probabilities/">확률 정보</a><a href="/support/">문의</a></div><div class="business-info">${c.legalEntity?esc(c.legalEntity):'Ludos Interactive'}${c.representative?` · 대표 ${esc(c.representative)}`:''}${c.businessAddress?`<br>${esc(c.businessAddress)}`:''}${c.businessNumber?`<br>사업자등록번호 ${esc(c.businessNumber)}`:''}${c.mailOrderStatus==='registered'?` · 통신판매업 신고 ${esc(c.mailOrderRegistration)} (${esc(c.mailOrderAuthority)})`:''}${c.businessPhone?`<br>대표전화 ${esc(c.businessPhone)}`:''}<br><a href="mailto:${c.supportEmail}">${c.supportEmail}</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Ludos Interactive.</span><span>GAMES, WITH CHARACTER.</span></div></footer>`;}
function layout(c,p,title,description,body,cls=''){const canonical=c.publicOrigin?`<link rel="canonical" href="${esc(c.publicOrigin+p)}">`:'';return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Ludos Interactive</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${c.isProduction?'index,follow':'noindex,nofollow'}"><meta name="theme-color" content="#101719"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} · Ludos Interactive"><meta property="og:description" content="${esc(description)}">${canonical}<link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><script src="/site.js" defer></script></head><body class="${cls}">${header(p)}<main id="main">${body}</main>${footer(c)}<dialog id="image-viewer" aria-label="게임 화면 크게 보기"><button class="dialog-close" aria-label="이미지 닫기">닫기 ×</button><img alt=""><p></p></dialog></body></html>`;}
function home(c){return `<section class="corporate-hero"><div class="hero-topline"><span>INDEPENDENT GAME STUDIO</span><span>게임을 만드는 사람들</span></div><h1>Ludos<br><span>Interactive.</span></h1><div class="corporate-intro"><p class="hero-statement">플레이의 즐거움이<br>오래 이어지도록.</p><div><p>작은 선택의 재미와 꾸준한 성장의 감각.<br>우리가 만들고 싶은 게임의 출발점입니다.</p>${link('#games','개발 작품 보기','text-link')}</div></div></section><section class="section games-section" id="games"><div class="section-heading"><div><p class="eyebrow">OUR WORK</p><h2>우리가 만드는 게임.</h2></div><p>각자의 세계, 같은 마음.<br>플레이어의 다음 시간을 생각합니다.</p></div><a class="featured-game" href="/games/kingdom-idle/"><div class="featured-art">${art()}<img class="game-logo" src="/assets/kingdom-logo.webp" alt="왕국군 키우기" width="768" height="539" loading="lazy"></div><div class="featured-info"><span class="status-label dark">개발 중</span><h3>왕국군 키우기</h3><p>병과와 장비, 마탑의 힘을 조합하는<br>도트 감성의 모바일 방치형 RPG.</p><dl><div><dt>장르</dt><dd>방치형 RPG</dd></div><div><dt>플랫폼</dt><dd>Android</dd></div><div><dt>출시 지역</dt><dd>대한민국 출시 준비</dd></div></dl><span class="text-link">게임 자세히 보기 ${arrow}</span></div></a></section><section class="studio-band"><div><p class="eyebrow light">OUR STUDIO</p><h2>게임의 기본에<br>집중합니다.</h2></div><div><p>플레이가 주는 즐거움, 읽기 쉬운 정보,<br>다시 돌아왔을 때 느끼는 성장.</p><p>작은 팀의 집중력으로 하나씩 다듬어 갑니다.</p>${link('/studio/','Ludos Interactive 소개','text-link light')}</div></section><section class="section support-section"><p class="eyebrow">PLAYER SUPPORT</p><div class="section-heading"><h2>게임 밖에서도,<br>쉽게 찾는 안내.</h2><p>이용 조건부터 개인정보와 계정 관리까지.<br>필요한 정보를 한곳에서 확인하세요.</p></div><div class="support-links">${link('/support/','게임 이용 문의','support-link')}${link('/policies/','약관과 개인정보 안내','support-link')}${link('/probabilities/','아이템 확률 정보','support-link')}</div></section>`;}
function studio(){return `<section class="page-intro studio-intro"><p class="eyebrow">LUDOS INTERACTIVE</p><h1>즐거운 선택을 만들고,<br>오래 이어질 모험을 만듭니다.</h1><p>우리는 모바일 게임을 만드는 작은 개발팀입니다.<br>지금은 「왕국군 키우기」의 전투와 성장 경험을 다듬고 있습니다.</p></section><div class="studio-signature"><span>LUDOS</span><p>즐거움에서 시작해,<br>플레이로 완성합니다.</p></div><section class="section"><div class="section-heading"><h2>우리가 중요하게<br>생각하는 것.</h2></div><div class="values"><article><span>01</span><h3>선택하는 재미</h3><p>병과와 장비, 스킬의 조합이 전투에 의미 있는 차이를 만들도록 설계합니다.</p></article><article><span>02</span><h3>편안한 흐름</h3><p>짧게 접속해도 지금의 성장과 다음 목표가 자연스럽게 보이도록 다듬습니다.</p></article><article><span>03</span><h3>명확한 안내</h3><p>게임 이용 조건과 보상 정보를 쉽게 찾고 이해할 수 있는 경험을 준비합니다.</p></article></div></section><section class="contact-band"><p>함께 이야기하고 싶다면</p><h2>Ludos Interactive에<br>연락해 주세요.</h2>${link('/support/','문의하기','button')}</section>`;}
function game(c){return `<section class="game-hero">${art(true)}<div class="game-hero-shade"></div><div class="game-hero-content"><span class="status-label">IN DEVELOPMENT</span><img class="game-title-logo" src="/assets/kingdom-logo.webp" width="768" height="539" alt="왕국군 키우기"><h1>작은 왕국군의<br>끝없는 성장.</h1><p>병과를 육성하고 장비와 마탑 스킬을 조합하는<br>도트 감성의 모바일 방치형 RPG.</p><span class="release-note">Android · 대한민국 출시 준비 중</span></div></section><div class="game-meta"><span><b>GENRE</b>방치형 RPG</span><span><b>PLATFORM</b>Android</span><span><b>DEVELOPER</b>Ludos Interactive</span></div><section class="section"><p class="eyebrow">BUILD YOUR KINGDOM</p><div class="section-heading"><h2>전투는 이어지고,<br>당신의 선택은 쌓입니다.</h2><p>성장에 맞는 장비를 고르고, 마탑의 힘을 더하세요.<br>보스와 던전, 환생을 거치며 왕국군의 가능성을 넓힙니다.</p></div><div class="game-features"><article><span>01 / ROYAL GUARD</span><h3>왕국군을 육성하세요</h3><p>병과의 역할과 능력을 살려 전투를 준비하고 성장의 방향을 선택하세요.</p></article><article><span>02 / EQUIPMENT & MAGIC</span><h3>당신만의 조합을 찾으세요</h3><p>장비와 마탑 스킬을 조합해 전투에 필요한 힘을 더하세요.</p></article><article><span>03 / KEEP GROWING</span><h3>돌아오면, 다시 한 걸음</h3><p>접속하지 않은 동안의 보상을 받고 다음 성장을 이어가세요. 최대 누적 시간은 6시간입니다.</p></article></div></section><section class="section gameplay-section" id="gameplay"><p class="eyebrow">IN-GAME</p><h2>왕국군의 하루를 만나보세요.</h2><p class="section-description">개발 중 실제 플레이 화면입니다. 출시 시 구성과 표현은 달라질 수 있습니다.</p><div class="screenshots" data-game-gallery>${gallery()}</div></section><section class="section game-help"><div><p class="eyebrow">GAME INFORMATION</p><h2>플레이 전에<br>확인하세요.</h2><p>현재 준비 중인 데모의 상점과 광고 보상은 미리보기입니다.<br>실제 결제와 광고 시청은 제공하지 않습니다.</p></div><div class="support-links">${link('/probabilities/','장비·마탑 확률 정보','support-link')}${link('/terms/','서비스 이용약관','support-link')}${link('/support/','게임 이용 문의','support-link')}</div></section>`;}
function support(c){return `<section class="page-intro"><p class="eyebrow">CONTACT & SUPPORT</p><h1>무엇을 도와드릴까요?</h1><p>게임 이용 중 궁금한 점이나 불편한 점을 알려 주세요.<br>문의 종류에 맞는 안내를 먼저 확인하실 수 있습니다.</p></section><section class="section support-layout"><div class="contact-card"><span class="eyebrow">왕국군 키우기 고객지원</span><h2>문의는 이메일로<br>보내 주세요.</h2><a class="email-link" href="mailto:${c.supportEmail}">${c.supportEmail}${arrow}</a><p>회신을 받을 이메일, 사용 기기, 게임 버전,<br>문제가 발생한 시점과 상황을 함께 적어 주세요.</p><p class="privacy-tip">비밀번호·인증 코드·전체 카드번호는 보내지 마세요.<br>스크린샷의 불필요한 개인정보도 가려 주세요.</p></div><div><h2 class="small-heading">바로 찾는 안내</h2><div class="support-links">${link('/delete-account/','계정과 데이터 삭제','support-link')}${link('/privacy/','개인정보 관련 권리 행사','support-link')}${link('/terms/#section-7','결제·환불 안내','support-link')}${link('/probabilities/','무작위 보상 확률','support-link')}</div><div class="support-note"><strong>현재 개발 중인 게임입니다.</strong><p>데모 상점의 상품·광고 버튼은 실제 결제나 광고 실행으로 연결되지 않습니다.</p></div></div></section><section class="section faq-section"><p class="eyebrow">FREQUENTLY ASKED QUESTIONS</p><h2>자주 찾는 질문</h2><details><summary>게임은 어디에서 다운로드할 수 있나요?</summary><p>현재 대한민국 Android 출시를 준비하고 있습니다. 배포가 시작되면 게임 소개 페이지에 공식 다운로드 경로를 안내하겠습니다.</p></details><details><summary>상점에서 구매 버튼을 눌러도 결제가 되지 않아요.</summary><p>현재 데모의 상점과 광고 보상은 UI 미리보기입니다. 실제 결제·광고 시청·상품 지급이 발생하지 않으며 준비 중 안내를 표시합니다.</p></details><details><summary>게임 계정 삭제와 Google 계정 삭제는 같은가요?</summary><p>서로 다릅니다. 이 사이트의 삭제 안내는 왕국군 키우기 계정과 회사가 처리하는 관련 데이터를 대상으로 합니다. Google 계정 자체를 삭제하지 않습니다.</p><a href="/delete-account/">계정 삭제 안내 보기</a></details><details><summary>다른 문의나 협업 제안은 어디로 보내면 되나요?</summary><p>같은 이메일로 문의하되 제목에 문의 목적을 적어 주세요. 수신한 내용을 확인할 수 있도록 구체적인 제안과 회신 주소를 함께 보내 주세요.</p></details></section>`;}
function policies(){return `<section class="page-intro"><p class="eyebrow">POLICIES & INFORMATION</p><h1>분명하게 안내합니다.</h1><p>게임 이용 조건, 개인정보 처리와 계정 관리.<br>플레이에 필요한 정보를 확인하세요.</p></section><section class="section policies-grid">${[['/privacy/','01','개인정보처리방침','처리하는 정보와 목적, 보유기간 및 권리 행사 방법'],['/terms/','02','서비스 이용약관','게임 이용, 상품과 환불, 회사와 이용자의 권리'],['/delete-account/','03','계정 삭제 안내','앱 안팎의 요청 방법과 삭제·보존 범위'],['/probabilities/','04','확률 정보','장비·마탑 보상 확률과 적용 조건']].map(([href,n,title,desc])=>`<a href="${href}" class="policy-card"><span>${n}</span><h2>${title}${arrow}</h2><p>${desc}</p></a>`).join('')}</section>`;}

function inline(s){return esc(s).replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|mailto:[^\s)]+|\/(?!\/)[^\s)]+|#[^\s)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');}
function markdown(source){const rows=source.replace(/\r/g,'').split('\n');let html='',list=false,table=false,heads=[];const closeList=()=>{if(list){html+='</ul>';list=false;}};const closeTable=()=>{if(table){html+='</tbody></table></div>';table=false;}};for(let i=0;i<rows.length;i++){const line=rows[i].trim();if(!line||line==='---'){closeList();closeTable();continue;}if(line.startsWith('<!--'))continue;if(/^\|[-: |]+\|$/.test(line))continue;if(line.startsWith('|')){closeList();const cells=line.split('|').slice(1,-1);if(!table){html+='<div class="table-wrap" tabindex="0" aria-label="좌우로 스크롤할 수 있는 안내 표"><table><thead><tr>'+cells.map(s=>`<th scope="col">${inline(s.trim())}</th>`).join('')+'</tr></thead><tbody>';table=true;}else html+='<tr>'+cells.map(s=>`<td>${inline(s.trim())}</td>`).join('')+'</tr>';continue;}closeTable();const h=line.match(/^(#{1,4})\s+(.+)/);if(h){closeList();const id=`section-${heads.length+1}`;const level=Math.max(2,h[1].length);heads.push({id,text:h[2]});html+=`<h${level} id="${id}">${inline(h[2])}</h${level}>`;continue;}if(/^[-*]\s/.test(line)||/^\d+\.\s/.test(line)){if(!list){html+='<ul>';list=true;}html+=`<li>${inline(line.replace(/^([-*]|\d+\.)\s/,''))}</li>`;continue;}closeList();html+=`<p>${inline(line)}</p>`;}closeList();closeTable();return {html,heads};}
async function policyBody(c,name,file){const full=await readFile(path.join(root,'../Docs/Publishing',file),'utf8');const start='<!-- PUBLIC-CONTENT:START -->',end='<!-- PUBLIC-CONTENT:END -->';const marked=full.includes(start)&&full.includes(end);const text=marked?full.split(start)[1].split(end)[0]:'';const doc=markdown(text);return `<section class="policy-intro"><p class="eyebrow">PLAYER INFORMATION</p><h1>${name}</h1><p>왕국군 키우기 · Ludos Interactive</p><div class="document-meta"><span>${c.effectiveDate?'시행일 '+esc(c.effectiveDate):'공개 전 검토본'}</span><span>검토일 ${c.reviewDate}</span></div></section><div class="document-layout"><aside class="document-nav"><details class="contents-toggle" open><summary>이 문서의 내용</summary><div class="contents-links">${doc.heads.filter(h=>h.text!==name).map(h=>`<a href="#${h.id}">${esc(h.text.replace(/\*\*/g,''))}</a>`).join('')}</div></details><a class="back-policies" href="/policies/">모든 정책 보기 ↗</a></aside><article class="document-body">${!c.isProduction?'<div class="review-notice"><strong>공개 전 검토 중인 문서입니다.</strong><p>실제 처리 내역과 운영 절차를 확인한 뒤 시행일을 정해 공개합니다. 아직 효력이 발생한 운영 정책이 아닙니다.</p></div>':''}${marked?doc.html:'<h2>문서를 준비하고 있습니다.</h2><p>정확한 서비스 정보와 운영 기준을 확인하고 있습니다. 확인된 전문이 준비되면 이 페이지에 반영합니다.</p>'}<div class="document-end"><p>이 문서에 대한 문의</p><a href="mailto:${c.supportEmail}">${c.supportEmail}</a></div></article></div>`;}
export async function build({production=false}={}) {
  const c=JSON.parse(await readFile(path.join(root,'content/site.json'),'utf8'));
  c.isProduction=production;
  if (production) await validatePublication(root,c);
  const output=path.resolve(root, production?'release':'dist');
  // Both directories contain generated files only. Never follow a linked output directory.
  if (path.dirname(output)!==root) throw new Error('Output must remain in Website');
  const info=await lstat(output).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
  if (info?.isSymbolicLink()) throw new Error('Refusing to replace a linked output directory');
  if (info) await rm(output,{recursive:true});
  await mkdir(output,{recursive:true});
  await cp(path.join(root,'public'),output,{recursive:true});
  for(const f of ['styles.css','site.js']) await cp(path.join(root,'src',f),path.join(output,f));
  const contents=new Map([['/',home(c)],['/games/kingdom-idle/',game(c)],['/studio/',studio()],['/support/',support(c)],['/policies/',policies()]]);
  for(const [route,title,file] of [
    ['/privacy/','개인정보처리방침','PRIVACY_POLICY_KO.md'],
    ['/terms/','서비스 이용약관','TERMS_OF_SERVICE_KO.md'],
    ['/delete-account/','계정 삭제 안내','ACCOUNT_DELETION_KO.md'],
    ['/probabilities/','확률 정보','PROBABILITY_DISCLOSURE.md']
  ]) contents.set(route,await policyBody(c,title,file));
  for(const p of pages) {
    const folder=path.join(output,p.path);
    await mkdir(folder,{recursive:true});
    const description=p.path==='/'?'Ludos Interactive. 플레이의 즐거움이 오래 이어지도록, 모바일 게임을 만듭니다.':`${c.brand}의 ${p.name}. 게임 정보와 이용 안내를 확인하세요.`;
    await writeFile(path.join(folder,'index.html'),layout(c,p.path,p.name,description,contents.get(p.path),p.path==='/'?'home-page':p.path.startsWith('/games/')?'game-page':''),'utf8');
  }
  await writeFile(path.join(output,'404.html'),layout(c,'/404','페이지를 찾을 수 없습니다','요청하신 페이지가 없습니다.',`<section class="page-intro error-page"><p class="eyebrow">404 / PAGE NOT FOUND</p><h1>다른 길로<br>가 볼까요?</h1><p>주소가 변경되었거나 페이지가 존재하지 않습니다.</p>${link('/','홈으로 돌아가기')}</section>`));
  await writeFile(path.join(output,'robots.txt'),production?`User-agent: *\nAllow: /\nSitemap: ${c.publicOrigin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
  if(production) await writeFile(path.join(output,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${esc(c.publicOrigin+p.path)}</loc></url>`).join('')}</urlset>`);
  return {pages:pages.length,production,output};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{console.log(await build({production:process.argv.includes('--production')}));}catch(e){console.error(e.message);process.exitCode=1;}}
